#!/bin/bash
#
# pcapsummary	This script is a front-end for running a plugin tap with
#		tshark.
#
#		This script was created for the GAWSEED project, part of
#		the CHASE program.
#
#		usage:	pcapsummary <file.pcap>
#
#		If a pcap file isn't given, then we'll default to reading
#		wireshark.pcap.
#
#
# Revision History
#	1.0	Initial revision.					190212
#	1.1	Renamed to sumwolf.					190219
#	1.2	Renamed to pcapsummary.					200206
#

#
# Version information.
#
NAME="pcapsummary"
VERS="pcapsummary version: 1.2"

#----------------------------------------------------------------------------

DEFPCAP="wireshark.pcap"

#
# Get the name of the pcap file to read.
#
PCAP=$DEFPCAP
if [ $# -gt 0 ]
then
	PCAP=$1
fi

TAP="pcap-summarizer.lua"

#
# Make sure the pcap file exists.  We'll let tshark check on accessibility.
#
if [ ! -e $PCAP ]
then
	echo pcap file \"$PCAP\" does not exist
	exit 1
fi

tshark -q -r $PCAP -X lua_script:$TAP -X lua_script1:-save=/tmp/pcap.summary

exit 0

